document.write(' 	<h1 class="acc-hidden"> 메인메뉴 </h1>	   ');
document.write(' 	<!-- // gnb 검색 -->   ');
document.write(' 	<div class="gnb_search_box">   ');
document.write(' 		<div class="gnb_search_bg">   ');
document.write(' 			<label for="f_gnbSearch" class="acc-hidden"> 검색어 입력</label>   ');
document.write(' 			<input type="search" id="f_gnbSearch" class="gnb_searchText"   placeholder="라필레어" onkeypress="if (event.keyCode==13){ go_search(); }">   ');
document.write(' 			<input type="submit" class="btn_gnbSearch" >   ');
document.write(' 		</div>    ');
document.write(' 	</div>    ');
document.write(' 	<!-- // gnb 검색 -->   ');
document.write(' 	<div class="gnb_box">   ');
document.write(' 		<ul class="gnb_ul">   ');
document.write(' 			<li> <a href="' + root + '/en/index.aspx"><span class="gnb_i_01">HOME</span></a> </li>   ');
document.write(' 			<li> <a href="#" ><span class="gnb_i_02">Company</span></a>    ');
document.write(' 				<ul  class="ly" style="display:none;">   ');
document.write(' 					<li><a href="' + root + '/en/intro/vision.aspx">Vision</a></li>   ');
document.write(' 					<li><a href="' + root + '/en/intro/leave.aspx"> History   </a></li>   ');
document.write(' 					<li><a href="' + root + '/en/intro/group.aspx">Organization Structure</a></li>   ');
document.write(' 					<li><a href="' + root + '/en/intro/location.aspx">Contact Us</a></li>   ');
document.write(' 				</ul>   ');
document.write(' 			</li>   ');
document.write(' 			<li> <a href="#"><span class="gnb_i_03"> Products </span></a>    ');
document.write(' 				<ul  class="ly" style="display:none;">   ');
document.write(' 					<li><a href="' + root + '/en/pdt/pdt_new_list.aspx?category=09&menu=0102">Pharmaceutical</a></li>   ');
document.write(' 					<li><a href="' + root + '/en/pdt/pdt_new_list.aspx?category=10&menu=0202">Animal Health & Nutrition</a></li>   ');
document.write(' 					<li><a href="' + root + '/en/pdt/bio_rnd.aspx?menu=0302">Bio</a></li>   ');
document.write(' 					<li><a href="' + root + '/en/pdt/pdt_list.aspx?category=12&menu=0401">International Sales</a></li>   ');
document.write(' 					<li><a href="' + root + '/en/pdt/pdt_list.aspx?category=15&menu=0501">Health Suppliments</a></li>   ');
document.write(' 					<li><a href="' + root + '/en/pdt/pdt_list.aspx?category=16&menu=0601">Medical Devices</a></li>   ');
document.write(' 				</ul>   ');
document.write(' 			</li>   ');
document.write(' 			<li>  <a href="#"><span class="gnb_i_05">Investors</span></a>    ');
document.write(' 				<ul  class="ly" style="display:none;">   ');
document.write(' 					<li><a href="' + root + '/en/inv/invest_ir_list.aspx">Prospective Investors</a></li>   ');
document.write(' 					<li><a href="' + root + '/en/inv/invest_money_mark.aspx">Financial Reports</a></li>   ');
document.write(' 					<li><a href="' + root + '/en/inv/stock_info.aspx">Shareholder Services</a></li>   ');
document.write(' 				</ul>   ');
document.write(' 			</li>   ');
document.write(' 			<li> <a href="#"><span class="gnb_i_06">Customer</span></a>    ');
document.write(' 				<ul  class="ly" style="display:none;">   ');
document.write(' 					<li><a href="' + root + '/en/cust/inquire_list.aspx">Product Q&A</a></li>   ');
document.write(' 					<li><a href="' + root + '/en/cust/with_list.aspx">Business Proposal</a></li>   ');
document.write(' 				</ul>   ');
document.write(' 			</li>   ');
document.write(' 		</ul>   ');
document.write(' 	</div>   ');
document.write(' 	<p class="gnb_copyright" > &copy;  Daehan New Pharm </p>   ');