document.write('  <meta charset="utf-8"> ');   
document.write('  <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">  ');
document.write('  <meta name="apple-mobile-web-app-capable" content="yes">   ');
document.write('  <title>대한뉴팜 모바일 </title>   ');
document.write('  <meta name="description" content="대한뉴팜의 소개와 제품소개입니다. ">  ');
document.write('  <meta name="keywords" content="대한뉴팜, 의약품 ">   ');
document.write('   <link rel="stylesheet" href="' + root + '/en/common/css/default.css">   ');
document.write('   <link rel="stylesheet" href="' + root + '/en/common/css/common.css">   ');
document.write('   <link rel="stylesheet" href="' + root + '/en/common/css/sub.css">   ');
document.write('   <link rel="stylesheet" href="' + root + '/en/common/css/jquery.bxslider.css">  ');
document.write('   <link rel="stylesheet" href="' + root + '/en/common/css/eng.css">  ');
document.write('   <link rel="stylesheet" href="' + root + '/common/css/jquery.remodal.css">  ');
document.write('   <script src="' + root + '/en/common/js/jquery-1.9.1.min.js" ></script>  ');
document.write('   <script src="' + root + '/en/common/js/jquery-ui-1.9.2.custom.min.js" ></script>   ');
document.write('   <script src="' + root + '/en/common/js/common.js" ></script>  ');
document.write('   <script src="' + root + '/en/common/js/jquery.bxslider.min.js" ></script>  ');
document.write('   <script src="' + root + '/common/js/jquery.remodal.js" ></script>  ');