
document.write('<div class="gnb">');   
document.write('<ul>');
document.write('    <li><a href="./member_list.html">회원</a>');
document.write('       <ul class="sub">');
document.write('              <li><a href="./member_list.html">회원</a></li>');
document.write('       </ul>');
document.write('    </li>');
document.write('    <li><a href="./diary_list.html">건강관리수첩 </a>');
document.write('       <ul class="sub">');
document.write('              <li><a href="./diary_list.html">기록지</a></li>');
document.write('              <li><a href="./diary_list_01.html">처방전</a></li>');
document.write('       </ul>');
document.write('   </li>');
document.write('	<li><a href="./movie_list.html"> 교육 및 칼럼 </a>');
document.write('       <ul class="sub">');
document.write('              <li><a href="./movie_list.html"> 교육 및 칼럼 </a></li>');
document.write('       </ul>');
document.write('    </li>');
document.write('	<li><a href="./healing_list.html">힐링음악 </a> ');
document.write('       <ul class="sub">');
document.write('              <li><a href="./healing_list.html"> 힐링음악 </a></li>');
document.write('       </ul>');
document.write('    </li>');
document.write('	<li><a href="./faq_list.html"> FAQ </a>');
document.write('       <ul class="sub">');
document.write('              <li><a href="./faq_list.html"> FAQ  </a></li>');
document.write('       </ul>');
document.write('    </li>');
document.write('	<li><a href="./question_list.html">문의사항 </a>');
document.write('       <ul class="sub">');
document.write('              <li><a href="./question_list.html">문의사항 </a></li>');
document.write('       </ul>');
document.write('    </li>');
document.write('	<li><a href="./hospital_list.html">병원리스트 </a>');
document.write('       <ul class="sub">');
document.write('              <li><a href="./hospital_list.html">병원리스트 </a></li>');
document.write('       </ul>');
document.write('    </li>');
document.write('	<li><a href="./order_list.html">계정정보</a>');
document.write('       <ul class="sub">');
document.write('              <li><a href="./order_list.html">계정정보</a></li>');
document.write('       </ul>');
document.write('    </li>');
document.write('</ul>');
document.write('</div>');

