document.write(' 	<h1 class="acc-hidden"> 메인메뉴 </h1>	   ');
document.write(' 	<!-- // gnb 검색 -->   ');
document.write(' 	<div class="gnb_search_box">   ');
document.write(' 		<div class="gnb_search_bg">   ');
document.write(' 			<label for="f_gnbSearch" class="acc-hidden"> 검색어 입력</label>   ');
document.write(' 			<input type="search" id="f_gnbSearch" class="gnb_searchText" placeholder="라필레어" onkeypress="if (event.keyCode==13){ go_search(); }">   ');
document.write(' 			<input type="button" onclick="javascript:go_search(); return false;" class="btn_gnbSearch" >   ');
document.write(' 		</div>    ');
document.write(' 	</div>    ');
document.write(' 	<!-- // gnb 검색 -->   ');
document.write(' 	<div class="gnb_box">   ');
document.write(' 		<ul class="gnb_ul">   ');
document.write(' 			<li> <a href="' + root +'/index.aspx"><span class="gnb_i_01"> HOME  </span></a> </li>   ');
document.write(' 			<li> <a href="#" ><span class="gnb_i_02">기업</span></a>    ');
document.write(' 				<ul  class="ly" style="display:none;">   ');
document.write(' 					<li><a href="' + root +'/intro/vision.aspx">비전</a></li>   ');
document.write(' 					<li><a href="' + root +'/intro/leave.aspx"> 발자취   </a></li>   ');
document.write(' 					<li><a href="' + root +'/intro/group.aspx">조직도</a></li>   ');
document.write(' 					<li><a href="' + root + '/intro/location.aspx"> 오시는 길  </a></li>   ');
document.write(' 				</ul>   ');
document.write(' 			</li>   ');
document.write(' 			<li> <a href="#"><span class="gnb_i_03"> 제품 </span></a>    ');
document.write(' 				<ul  class="ly" style="display:none;">   ');
document.write(' 					<li><a href="' + root + '/pdt/pdt_human_new_list.aspx"> 인체 의약품 </a></li>   ');
document.write(' 					<li><a href="' + root + '/pdt/pdt_animal_new_list.aspx"> 동물 의약품 </a></li>   ');
document.write(' 					<li><a href="' + root + '/pdt/pdt_bio_badge_list.aspx"> 바이오 공정소재</a></li>   ');
document.write(' 					<li><a href="' + root + '/pdt/pdt_global_human_list.aspx"> 수출 의약품 </a></li>   ');
document.write(' 					<li><a href="' + root + '/pdt/pdt_health_list.aspx"> 건강기능식품  </a></li>   ');
document.write(' 					<li><a href="' + root + '/pdt/pdt_medical_list.aspx"> 의료기기  </a></li>   ');
document.write(' 				</ul>   ');
document.write(' 			</li>   ');
document.write(' 			<li> <a href="#"><span class="gnb_i_04"> 홍보 </span></a>    ');
document.write(' 				<ul  class="ly" style="display:none;">   ');
document.write(' 					<li><a href="' + root + '/pr/pr_new_list.aspx"> 새소식 </a></li>   ');
document.write(' 					<li><a href="' + root + '/pr/pr_global_list.aspx">해외자원투자</a></li>   ');
document.write(' 				</ul>   ');
document.write(' 			</li>   ');
document.write(' 			<li>  <a href="#"><span class="gnb_i_05">  투자 </span></a>    ');
document.write(' 				<ul  class="ly" style="display:none;">   ');
document.write(' 					<li><a href="' + root + '/inv/invest_ir_list.aspx"> 경영정보 </a></li>   ');
document.write(' 					<li><a href="' + root + '/inv/invest_money_mark.aspx"> 재무정보 </a></li>   ');
document.write(' 					<li><a href="' + root + '/inv/stock_info.aspx"> 주식정보</a></li>   ');
document.write(' 					<li><a href="' + root + '/inv/invest_notice_list.aspx"> 공고사항</a></li>   ');
document.write(' 				</ul>   ');
document.write(' 			</li>   ');
document.write(' 			<li> <a href="#"><span class="gnb_i_06">  고객 </span></a>    ');
document.write(' 				<ul  class="ly" style="display:none;">   ');
document.write(' 					<li><a href="' + root + '/cust/inquire_list.aspx"> 제품문의 </a></li>   ');
document.write(' 					<li><a href="' + root + '/cust/with_list.aspx"> 제휴제안 </a></li>   ');
document.write(' 				</ul>   ');
document.write(' 			</li>   ');
document.write(' 		</ul>   ');
document.write(' 	</div>   ');
document.write(' 	<p class="gnb_copyright" > &copy;  Daehan New Pharm </p>   ');